export type GoogleFontDefinition = {
  category: "playful" | "sans" | "serif";
  family: string;
  googleFamily: string;
  id: string;
  label: string;
  license: string;
  matchKind: "exact" | "near" | "substitute";
  vendorPath: string;
};

export const googleFonts = [
  {
    category: "playful",
    family: "Love Ya Like A Sister",
    googleFamily: "Love Ya Like A Sister",
    id: "google-love-ya-like-a-sister",
    label: "Love Ya Like A Sister",
    license: "SIL Open Font License 1.1",
    matchKind: "exact",
    vendorPath:
      "vendor/fonts/google-fonts/google-love-ya-like-a-sister-LoveYaLikeASister-Regular.ttf",
  },
  {
    category: "serif",
    family: "Baskerville",
    googleFamily: "Libre Baskerville",
    id: "google-baskerville",
    label: "Baskerville",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-baskerville-kmKUZrc3Hgbbcjq75U4uslyuy4kn0olVQ-LglH6T17uj8Q4SCQ.ttf",
  },
  {
    category: "serif",
    family: "Bodoni Bauer",
    googleFamily: "Bodoni Moda",
    id: "google-bodoni-bauer",
    label: "Bodoni Bauer",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-bodoni-bauer-aFT67PxzY382XsXX63LUYL6GYFcan6NJrKp-VPjfJMShrpsGFUt8oU7awIA.ttf",
  },
  {
    category: "serif",
    family: "Bodoni Italic",
    googleFamily: "Bodoni Moda",
    id: "google-bodoni-italic",
    label: "Bodoni Italic",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-bodoni-italic-aFT07PxzY382XsXX63LUYJSPUqb0pL6OQqxrZLnVbvZedvJtj-V7tIaZKMN4sQ.ttf",
  },
  {
    category: "serif",
    family: "Bodoni Ultra Bold",
    googleFamily: "Bodoni Moda",
    id: "google-bodoni-ultra-bold",
    label: "Bodoni Ultra Bold",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-bodoni-ultra-bold-aFT67PxzY382XsXX63LUYL6GYFcan6NJrKp-VPjfJMShrpsGFUt8oefdwIA.ttf",
  },
  {
    category: "serif",
    family: "Bodoni",
    googleFamily: "Bodoni Moda",
    id: "google-bodoni",
    label: "Bodoni",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-bodoni-bauer-aFT67PxzY382XsXX63LUYL6GYFcan6NJrKp-VPjfJMShrpsGFUt8oU7awIA.ttf",
  },
  {
    category: "serif",
    family: "Caslon Bold Italic",
    googleFamily: "Libre Caslon Text",
    id: "google-caslon-bold-italic",
    label: "Caslon Bold Italic",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-caslon-bold-italic-DdT678IGsGw1aF1JU10PUbTvNNaDMfq91-c.ttf",
  },
  {
    category: "serif",
    family: "Caslon Bold",
    googleFamily: "Libre Caslon Text",
    id: "google-caslon-bold",
    label: "Caslon Bold",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-caslon-bold-DdT578IGsGw1aF1JU10PUbTvNNaDMfID8sdj.ttf",
  },
  {
    category: "serif",
    family: "Caslon Italic",
    googleFamily: "Libre Caslon Text",
    id: "google-caslon-italic",
    label: "Caslon Italic",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-caslon-bold-italic-DdT678IGsGw1aF1JU10PUbTvNNaDMfq91-c.ttf",
  },
  {
    category: "serif",
    family: "Caslon",
    googleFamily: "Libre Caslon Text",
    id: "google-caslon",
    label: "Caslon",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath: "vendor/fonts/google-fonts/google-caslon-DdT878IGsGw1aF1JU10PUbTvNNaDMcq_.ttf",
  },
  {
    category: "playful",
    family: "Freehand",
    googleFamily: "Freehand",
    id: "google-freehand",
    label: "Freehand",
    license: "Google Fonts open source license",
    matchKind: "exact",
    vendorPath: "vendor/fonts/google-fonts/google-freehand-cIf-Ma5eqk01VjKTgAmB.ttf",
  },
  {
    category: "serif",
    family: "Garamond Bold",
    googleFamily: "EB Garamond",
    id: "google-garamond-bold",
    label: "Garamond Bold",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-garamond-bold-SlGDmQSNjdsmc35JDF1K5E55YMjF_7DPuGi-DPNUAw.ttf",
  },
  {
    category: "serif",
    family: "Garamond Condensed",
    googleFamily: "EB Garamond",
    id: "google-garamond-condensed",
    label: "Garamond Condensed",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-garamond-condensed-SlGDmQSNjdsmc35JDF1K5E55YMjF_7DPuGi-6_RUAw.ttf",
  },
  {
    category: "serif",
    family: "Garamond Italic",
    googleFamily: "EB Garamond",
    id: "google-garamond-italic",
    label: "Garamond Italic",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-garamond-italic-SlGFmQSNjdsmc35JDF1K5GRwUjcdlttVFm-rI7e8QI96.ttf",
  },
  {
    category: "serif",
    family: "Garamond",
    googleFamily: "EB Garamond",
    id: "google-garamond",
    label: "Garamond",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-garamond-condensed-SlGDmQSNjdsmc35JDF1K5E55YMjF_7DPuGi-6_RUAw.ttf",
  },
  {
    category: "serif",
    family: "Goudy Old Style Bold",
    googleFamily: "Sorts Mill Goudy",
    id: "google-goudy-old-style-bold",
    label: "Goudy Old Style Bold",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-goudy-old-style-bold-Qw3GZR9MED_6PSuS_50nEaVrfzgEXH0.ttf",
  },
  {
    category: "serif",
    family: "Goudy Old Style Italic",
    googleFamily: "Sorts Mill Goudy",
    id: "google-goudy-old-style-italic",
    label: "Goudy Old Style Italic",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-goudy-old-style-italic-Qw3AZR9MED_6PSuS_50nEaVrfzgEbH8Eig.ttf",
  },
  {
    category: "serif",
    family: "Goudy Old Style",
    googleFamily: "Sorts Mill Goudy",
    id: "google-goudy-old-style",
    label: "Goudy Old Style",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-goudy-old-style-bold-Qw3GZR9MED_6PSuS_50nEaVrfzgEXH0.ttf",
  },
  {
    category: "playful",
    family: "Monte Carlo",
    googleFamily: "MonteCarlo",
    id: "google-monte-carlo",
    label: "Monte Carlo",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath: "vendor/fonts/google-fonts/google-monte-carlo-buEzpo6-f9X01GadLA0G0Co.ttf",
  },
  {
    category: "serif",
    family: "New Baskerville Bold",
    googleFamily: "Baskervville",
    id: "google-new-baskerville-bold",
    label: "New Baskerville Bold",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-new-baskerville-bold-YA9Br0yU4l_XOrogbkun3kQ6vLFYXmpq8sRsYgfsugM.ttf",
  },
  {
    category: "serif",
    family: "New Baskerville Italic",
    googleFamily: "Baskervville",
    id: "google-new-baskerville-italic",
    label: "New Baskerville Italic",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-new-baskerville-italic-YA9Hr0yU4l_XOrogbkun3kQQtYOnhgMBaGprdyioUkC4cQ.ttf",
  },
  {
    category: "serif",
    family: "New Baskerville SC Bold",
    googleFamily: "Baskervville SC",
    id: "google-new-baskerville-sc-bold",
    label: "New Baskerville SC Bold",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-new-baskerville-sc-bold-X7ny4bc_DeKlh6bBbk_WiKnBSUvL5HaHbrgS1MXKHtvlXM0.ttf",
  },
  {
    category: "serif",
    family: "New Baskerville SC Italic",
    googleFamily: "Baskervville SC",
    id: "google-new-baskerville-sc-italic",
    label: "New Baskerville SC Italic",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-new-baskerville-sc-italic-X7ny4bc_DeKlh6bBbk_WiKnBSUvL5HaHbrgS1MXKHjziXM0.ttf",
  },
  {
    category: "serif",
    family: "New Baskerville",
    googleFamily: "Baskervville",
    id: "google-new-baskerville",
    label: "New Baskerville",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath:
      "vendor/fonts/google-fonts/google-new-baskerville-YA9Br0yU4l_XOrogbkun3kQ6vLFYXmpq8sRsYuDrugM.ttf",
  },
  {
    category: "playful",
    family: "Pacifico",
    googleFamily: "Pacifico",
    id: "google-pacifico",
    label: "Pacifico",
    license: "Google Fonts open source license",
    matchKind: "exact",
    vendorPath: "vendor/fonts/google-fonts/google-pacifico-FwZY7-Qmy14u9lezJ96A.ttf",
  },
  {
    category: "playful",
    family: "Square Peg",
    googleFamily: "Square Peg",
    id: "google-square-peg",
    label: "Square Peg",
    license: "Google Fonts open source license",
    matchKind: "exact",
    vendorPath: "vendor/fonts/google-fonts/google-square-peg-y83eW48Nzw6ZlUHc-phrBDE.ttf",
  },
  {
    category: "playful",
    family: "Water Brush",
    googleFamily: "Water Brush",
    id: "google-water-brush",
    label: "Water Brush",
    license: "Google Fonts open source license",
    matchKind: "exact",
    vendorPath: "vendor/fonts/google-fonts/google-water-brush-AYCPpXPqc8cJWLhp4hywKHJq.ttf",
  },
  {
    category: "playful",
    family: "Wendy",
    googleFamily: "Wendy One",
    id: "google-wendy",
    label: "Wendy",
    license: "Google Fonts open source license",
    matchKind: "near",
    vendorPath: "vendor/fonts/google-fonts/google-wendy-2sDcZGJOipXfgfXV5wgDbw.ttf",
  },
  {
    category: "sans",
    family: "Arial",
    googleFamily: "Arimo",
    id: "google-arial",
    label: "Arial",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath: "vendor/fonts/google-fonts/google-arial-P5sfzZCDf9_T_3cV7NCUECyoxNk37cxsBw.ttf",
  },
  {
    category: "sans",
    family: "Avant Garde Bold Italic",
    googleFamily: "Montserrat",
    id: "google-avant-garde-bold-italic",
    label: "Avant Garde Bold Italic",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-avant-garde-bold-italic-JTUFjIg1_i6t8kCHKm459Wx7xQYXK0vOoz6jq0N6aX8.ttf",
  },
  {
    category: "sans",
    family: "Avant Garde Bold",
    googleFamily: "Montserrat",
    id: "google-avant-garde-bold",
    label: "Avant Garde Bold",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-avant-garde-bold-JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCuM70w-.ttf",
  },
  {
    category: "sans",
    family: "Avant Garde Italic",
    googleFamily: "Montserrat",
    id: "google-avant-garde-italic",
    label: "Avant Garde Italic",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-avant-garde-italic-JTUFjIg1_i6t8kCHKm459Wx7xQYXK0vOoz6jq6R9aX8.ttf",
  },
  {
    category: "sans",
    family: "Avant Garde",
    googleFamily: "Montserrat",
    id: "google-avant-garde",
    label: "Avant Garde",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-avant-garde-JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCtr6Ew-.ttf",
  },
  {
    category: "sans",
    family: "Avenir Bold",
    googleFamily: "Nunito Sans",
    id: "google-avenir-bold",
    label: "Avenir Bold",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-avenir-bold-pe1mMImSLYBIv1o4X1M8ce2xCx3yop4tQpF_MeTm0lfGWVpNn64CL7U8upHZIbMV51Q42ptCp5F5bxqqtQ1yiU4GMS5ntA.ttf",
  },
  {
    category: "sans",
    family: "Avenir Italic",
    googleFamily: "Nunito Sans",
    id: "google-avenir-italic",
    label: "Avenir Italic",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-avenir-italic-pe1kMImSLYBIv1o4X1M8cce4OdVisMz5nZRqy6cmmmU3t2FQWEAEOvV9wNvrwlNstMKW3Y6K5WMwXeVy3GboJ0kTHmqP91Ug.ttf",
  },
  {
    category: "sans",
    family: "Avenir",
    googleFamily: "Nunito Sans",
    id: "google-avenir",
    label: "Avenir",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-avenir-pe1mMImSLYBIv1o4X1M8ce2xCx3yop4tQpF_MeTm0lfGWVpNn64CL7U8upHZIbMV51Q42ptCp5F5bxqqtQ1yiU4G1ilntA.ttf",
  },
  {
    category: "sans",
    family: "Century Gothic Bold",
    googleFamily: "Questrial",
    id: "google-century-gothic-bold",
    label: "Century Gothic Bold",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath: "vendor/fonts/google-fonts/google-century-gothic-bold-QdVUSTchPBm7nuUeVf7EuQ.ttf",
  },
  {
    category: "sans",
    family: "Century Gothic",
    googleFamily: "Questrial",
    id: "google-century-gothic",
    label: "Century Gothic",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath: "vendor/fonts/google-fonts/google-century-gothic-bold-QdVUSTchPBm7nuUeVf7EuQ.ttf",
  },
  {
    category: "serif",
    family: "Copperplate",
    googleFamily: "Cinzel",
    id: "google-copperplate",
    label: "Copperplate",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-copperplate-8vIU7ww63mVu7gtR-kwKxNvkNOjw-tbnTYo.ttf",
  },
  {
    category: "sans",
    family: "Futura Com Bold",
    googleFamily: "Jost",
    id: "google-futura-com-bold",
    label: "Futura Com Bold",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-futura-com-bold-92zPtBhPNqw79Ij1E865zBUv7mxEIgVG.ttf",
  },
  {
    category: "sans",
    family: "Futura Com Light",
    googleFamily: "Jost",
    id: "google-futura-com-light",
    label: "Futura Com Light",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-futura-com-light-92zPtBhPNqw79Ij1E865zBUv7mz9JQVG.ttf",
  },
  {
    category: "sans",
    family: "Futura Com Medium Condensed",
    googleFamily: "Jost",
    id: "google-futura-com-medium-condensed",
    label: "Futura Com Medium Condensed",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-futura-com-medium-condensed-92zPtBhPNqw79Ij1E865zBUv7myRJQVG.ttf",
  },
  {
    category: "sans",
    family: "Futura Com",
    googleFamily: "Jost",
    id: "google-futura-com",
    label: "Futura Com",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath: "vendor/fonts/google-fonts/google-futura-com-92zPtBhPNqw79Ij1E865zBUv7myjJQVG.ttf",
  },
  {
    category: "sans",
    family: "Futura LT Bold",
    googleFamily: "Jost",
    id: "google-futura-lt-bold",
    label: "Futura LT Bold",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-futura-com-bold-92zPtBhPNqw79Ij1E865zBUv7mxEIgVG.ttf",
  },
  {
    category: "sans",
    family: "Futura LT Italic",
    googleFamily: "Jost",
    id: "google-futura-lt-italic",
    label: "Futura LT Italic",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-futura-lt-italic-92zJtBhPNqw73oHH7BbQp4-B6XlrZu0FNI0.ttf",
  },
  {
    category: "sans",
    family: "Futura LT Light",
    googleFamily: "Jost",
    id: "google-futura-lt-light",
    label: "Futura LT Light",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-futura-com-light-92zPtBhPNqw79Ij1E865zBUv7mz9JQVG.ttf",
  },
  {
    category: "sans",
    family: "Futura LT",
    googleFamily: "Jost",
    id: "google-futura-lt",
    label: "Futura LT",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath: "vendor/fonts/google-fonts/google-futura-com-92zPtBhPNqw79Ij1E865zBUv7myjJQVG.ttf",
  },
  {
    category: "sans",
    family: "Gill Sans",
    googleFamily: "Lato",
    id: "google-gill-sans",
    label: "Gill Sans",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath: "vendor/fonts/google-fonts/google-gill-sans-S6uyw4BMUTPHvxk.ttf",
  },
  {
    category: "sans",
    family: "Helvetica Condensed",
    googleFamily: "Roboto Condensed",
    id: "google-helvetica-condensed",
    label: "Helvetica Condensed",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-helvetica-condensed-ieVo2ZhZI2eCN5jzbjEETS9weq8-_d6T_POl0fRJeyWyovBJ.ttf",
  },
  {
    category: "sans",
    family: "Helvetica Neue Bold",
    googleFamily: "Roboto",
    id: "google-helvetica-neue-bold",
    label: "Helvetica Neue Bold",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-helvetica-neue-bold-KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjammT.ttf",
  },
  {
    category: "sans",
    family: "Helvetica Neue Light",
    googleFamily: "Roboto",
    id: "google-helvetica-neue-light",
    label: "Helvetica Neue Light",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-helvetica-neue-light-KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabWmT.ttf",
  },
  {
    category: "sans",
    family: "Helvetica Neue",
    googleFamily: "Roboto",
    id: "google-helvetica-neue",
    label: "Helvetica Neue",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath:
      "vendor/fonts/google-fonts/google-helvetica-neue-KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbWmT.ttf",
  },
  {
    category: "serif",
    family: "Times New Roman",
    googleFamily: "Tinos",
    id: "google-times-new-roman",
    label: "Times New Roman",
    license: "Google Fonts open source license",
    matchKind: "substitute",
    vendorPath: "vendor/fonts/google-fonts/google-times-new-roman-buE4poGnedXvwgX8.ttf",
  },
] as const satisfies readonly GoogleFontDefinition[];

export type GoogleFontId = (typeof googleFonts)[number]["id"];
